### PR TITLE
Add opcodes 3d 3e and fd...

### PR DESCRIPTION
**Pull request by rocky**
Reduce size of fields.

Alas there are gratuitous space differences.

If you want me to break this down and reduce gratuitous white space I can do that.

### CODE REVIEW

**Comment by tintinweb** [comment]
:+1: thx

**Comment by rocky** [comment]
For what it's worth, I have started making more larger changes and expansions to this code over at https://github.com/rocky/ethereum-dasm 

The main thing currently added is starting to integrate assemebly information solc's source to bytecode mappings which is also include in truffle.

Although I've started this, down the line I think the opcode might be totally split off from the instructions, and that way there can be a couple of different sets: e.g the original version of the opcodes the version of the opcodes after the last set and so on. 

I'm thinking of modeling everython more like https://github.com/rocky/python-xdis which in truth models things more like Python's opcodes. 

And to that end one small change I've started to make and will pursue later is that there should be formatting routines off of the instruction and then removed from the the printing routines that work off sequences of instructions.  

How that helps here, is that in the solc source to bytecode map, then I can just displlay the single instruction as it relates to an entry in the map.

**Comment by tintinweb** [comment]
Hi @rocky,

contributions are very welcome and if you want to contribute please avoid unnecessary dependencies (stay cross platform, avoid the compiler mess). 
btw I've added a setup.py, fixed some imports and style issues and removed a debugging leftover (`from trepan.api import debug; debug()`).

cheers,
tin

**Comment by rocky** [comment]
I am very sorry about the trepan.api leftover. It was not intentional. 

I make lots of mistakes (and that was one of them). But then, that's why I work on debuggers. 

Some of the sourcemap stuff is in https://github.com/rocky/ethereum-dasm/commit/5a7cfa2fc776167b5a1427d2f8d488e0e6b1e068  but it's in great flux and there probably will be a lot of reorganization. There are still some mysteries matching up what the solc docs say should be there and what is seen, but for the part that works, I like it.

**Comment by tintinweb** [comment]
Hi @rocky,

maybe [evmlab/source_map.py](https://github.com/holiman/evmlab/blob/master/evmlab/source_map.py) can help demystify it a bit (besides evmlab being an awesome project)

Happy to merge features if you have something with minimal changes and minimal dependencies that works :+1: 

cheers,
tin

**Comment by rocky** [comment]
Thanks for the pointer. Will look at later.

**Pull request merged**
